[project]
name = "valgem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0.post0",
    "httpx>=0.28.1",
    "orjson>=3.10.18",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "mypy>=1.16.1",
]
